routes/admin.php
<?php

Route::get('/home', function () {
    $users[] = Auth::user();
    $users[] = Auth::guard()->user();
    $users[] = Auth::guard('admin')->user();

    //dd($users);

    return view('admin.dashboard.index');
})->name('home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {
  Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
  Route::post('/login', 'AdminAuth\LoginController@login')->name('postLogin');
  Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');
  
  // Disable admin registration
  // Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
  // Route::post('/register', 'AdminAuth\RegisterController@register')->name('postRegister');
  
  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm')->name('showResetForm');;
   });

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="./favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Site title -->
    <title>{{ config('app.name', 'KRAS Admin') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('/js/manifest.js') }}"></script>
    <script src="{{ asset('/js/vendor.js') }}"></script>
    <script src="{{ asset('/js/app.js') }}"></script>
    @stack('scripts')

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">   
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
@yield('content')
</html>

resources/views/admin/layouts/footer.blade.php
<div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="row">
            <div class="col-6 col-md-3">
              <ul class="list-unstyled mb-0">
                <li><a href="#">First link</a></li>
                <li><a href="#">Second link</a></li>
              </ul>
            </div>
            <div class="col-6 col-md-3">
              <ul class="list-unstyled mb-0">
                <li><a href="#">Third link</a></li>
                <li><a href="#">Fourth link</a></li>
              </ul>
            </div>
            <div class="col-6 col-md-3">
              <ul class="list-unstyled mb-0">
                <li><a href="#">Fifth link</a></li>
                <li><a href="#">Sixth link</a></li>
              </ul>
            </div>
            <div class="col-6 col-md-3">
              <ul class="list-unstyled mb-0">
                <li><a href="#">Other link</a></li>
                <li><a href="#">Last link</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-4 mt-4 mt-lg-0">
          Premium and Open Source dashboard template with responsive and high
          quality UI. For Free!
        </div>
      </div>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <div class="row align-items-center flex-row-reverse">
        <div class="col-auto ml-lg-auto">
          <div class="row align-items-center">
            <div class="col-auto">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item">
                  <a href="./docs/index.html">Documentation</a>
                </li>
                <li class="list-inline-item"><a href="./faq.html">FAQ</a></li>
              </ul>
            </div>
            <div class="col-auto">
              <a
                href="https://github.com/tabler/tabler"
                class="btn btn-outline-primary btn-sm"
                >Source code</a
              >
            </div>
          </div>
        </div>
        <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
          Copyright © 2018 <a href=".">Tabler</a>. Theme by
          <a href="https://codecalm.net" target="_blank">codecalm.net</a> All
          rights reserved.
        </div>
      </div>
    </div>
  </footer>

resources/views/admin/layouts/header.blade.php
<div class="header py-4">
    <div class="container">
      <div class="d-flex">
        <a class="header-brand" href="{{ route('admin.home') }}">
          <img
            src="{{ $logo_url }}"
            class="header-brand-img"
            alt="tabler logo"
          />
        </a>
        <div class="d-flex order-lg-2 ml-auto">
          <div class="nav-item d-none d-md-flex">
            <a
              href="#"
              class="btn btn-sm btn-outline-primary"
              >Button here</a
            >
          </div>
          <div class="dropdown d-none d-md-flex">
            <a class="nav-link icon" data-toggle="dropdown">
              <i class="fe fe-bell"></i>
              <span class="nav-unread"></span>
            </a>
            <div
              class="dropdown-menu dropdown-menu-right dropdown-menu-arrow"
            >
              <a href="#" class="dropdown-item d-flex">
                <span
                  class="avatar mr-3 align-self-center"
                  style="background-image: url(https://robohash.org/41.jpg?size=64x64)"
                ></span>
                <div>
                  <strong>Nathan</strong> pushed new commit: Fix page load
                  performance issue.
                  <div class="small text-muted">10 minutes ago</div>
                </div>
              </a>
              <a href="#" class="dropdown-item d-flex">
                <span
                  class="avatar mr-3 align-self-center"
                  style="background-image: url(https://robohash.org/1.jpg?size=64x64)"
                ></span>
                <div>
                  <strong>Alice</strong> started new task: Tabler UI design.
                  <div class="small text-muted">1 hour ago</div>
                </div>
              </a>
              <a href="#" class="dropdown-item d-flex">
                <span
                  class="avatar mr-3 align-self-center"
                  style="background-image: url(https://robohash.org/18.jpg?size=64x64)"
                ></span>
                <div>
                  <strong>Rose</strong> deployed new version of NodeJS REST
                  Api V3
                  <div class="small text-muted">2 hours ago</div>
                </div>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item text-center text-muted-dark"
                >Mark all as read</a
              >
            </div>
          </div>
          <div class="dropdown">
            <a
              href="#"
              class="nav-link pr-0 leading-none"
              data-toggle="dropdown"
            >
              <span
                class="avatar"
                style="background-image: url(https://robohash.org/25.jpg?size=64x64)"
              ></span>
              <span class="ml-2 d-none d-lg-block">
                <span class="text-default">{{ $user->name }}</span>
                <small class="text-muted d-block mt-1">Administrator</small>
              </span>
            </a>
            <div
              class="dropdown-menu dropdown-menu-right dropdown-menu-arrow"
            >
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fe fe-user"></i> Profile
              </a>
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fe fe-settings"></i> Settings
              </a>
              <a class="dropdown-item" href="#">
                <span class="float-right"
                  ><span class="badge badge-primary">6</span></span
                >
                <i class="dropdown-icon fe fe-mail"></i> Inbox
              </a>
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fe fe-send"></i> Message
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">
                <i class="dropdown-icon fe fe-help-circle"></i> Need help?
              </a>
              <a class="dropdown-item" href="{{ route('admin.logout') }}" 
                onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <i class="dropdown-icon fe fe-log-out"></i> {{ __('Logout') }}
              </a>
              <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>              
            </div>
          </div>
        </div>
        <a
          href="#"
          class="header-toggler d-lg-none ml-3 ml-lg-0"
          data-toggle="collapse"
          data-target="#headerMenuCollapse"
        >
          <span class="header-toggler-icon"></span>
        </a>
      </div>
    </div>
  </div>

resources/views/admin/layouts/menubar.blade.php
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-3 ml-auto">
          <form class="input-icon my-3 my-lg-0">
            <input
              type="search"
              class="form-control header-search"
              placeholder="Search&hellip;"
              tabindex="1"
            />
            <div class="input-icon-addon">
              <i class="fe fe-search"></i>
            </div>
          </form>
        </div>
        <div class="col-lg order-lg-first">
          <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
            <li class="nav-item">
              <a href="./index.html" class="nav-link active"
                ><i class="fe fe-home"></i> Home</a
              >
            </li>
            <li class="nav-item">
              <a
                href="javascript:void(0)"
                class="nav-link"
                data-toggle="dropdown"
                ><i class="fe fe-box"></i> Interface</a
              >
              <div class="dropdown-menu dropdown-menu-arrow">
                <a href="./cards.html" class="dropdown-item "
                  >Cards design</a
                >
                <a href="./charts.html" class="dropdown-item ">Charts</a>
                <a href="./pricing-cards.html" class="dropdown-item "
                  >Pricing cards</a
                >
              </div>
            </li>
            <li class="nav-item dropdown">
              <a
                href="javascript:void(0)"
                class="nav-link"
                data-toggle="dropdown"
                ><i class="fe fe-calendar"></i> Components</a
              >
              <div class="dropdown-menu dropdown-menu-arrow">
                <a href="./maps.html" class="dropdown-item ">Maps</a>
                <a href="./icons.html" class="dropdown-item ">Icons</a>
                <a href="./store.html" class="dropdown-item ">Store</a>
                <a href="./blog.html" class="dropdown-item ">Blog</a>
                <a href="./carousel.html" class="dropdown-item "
                  >Carousel</a
                >
              </div>
            </li>
            <li class="nav-item dropdown">
              <a
                href="javascript:void(0)"
                class="nav-link"
                data-toggle="dropdown"
                ><i class="fe fe-file"></i> Pages</a
              >
              <div class="dropdown-menu dropdown-menu-arrow">
                <a href="./profile.html" class="dropdown-item ">Profile</a>
                <a href="./login.html" class="dropdown-item ">Login</a>
                <a href="./register.html" class="dropdown-item "
                  >Register</a
                >
                <a href="./forgot-password.html" class="dropdown-item "
                  >Forgot password</a
                >
                <a href="./400.html" class="dropdown-item ">400 error</a>
                <a href="./401.html" class="dropdown-item ">401 error</a>
                <a href="./403.html" class="dropdown-item ">403 error</a>
                <a href="./404.html" class="dropdown-item ">404 error</a>
                <a href="./500.html" class="dropdown-item ">500 error</a>
                <a href="./503.html" class="dropdown-item ">503 error</a>
                <a href="./email.html" class="dropdown-item ">Email</a>
                <a href="./empty.html" class="dropdown-item ">Empty page</a>
                <a href="./rtl.html" class="dropdown-item ">RTL mode</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a href="./form-elements.html" class="nav-link"
                ><i class="fe fe-check-square"></i> Forms</a
              >
            </li>
            <li class="nav-item">
              <a href="./gallery.html" class="nav-link"
                ><i class="fe fe-image"></i> Gallery</a
              >
            </li>
            <li class="nav-item">
              <a href="./docs/index.html" class="nav-link"
                ><i class="fe fe-file-text"></i> Documentation</a
              >
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

resources/views/admin/layouts/page.blade.php
@extends('admin.layouts.app') @section('content')
<body class="">
  <div class="page">
    <div class="page-main">
      <!-- Begin of Header -->
      @include('admin.layouts.header')
      <!-- End of Header -->

      <!-- Begin of Menu Bar -->
      @include('admin.layouts.menubar')
      <!-- End of Menu Bar -->

      <!-- Begin of Page Content -->
      @yield('pagecontent')
      <!-- End of Page Content -->
    </div>
    <!-- Begin of Footer -->
    @include('admin.layouts.footer')
    <!-- End of Footer -->
  </div>
</body>
@endsection